owgw:
  services:
    owgw:
      type: ClusterIP
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "none"

owsec:
  services:
    owsec:
      type: ClusterIP
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "none"

rttys:
  services:
    rttys:
      type: ClusterIP
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "none"

owfms:
  services:
    owfms:
      type: ClusterIP
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "none"

owprov:
  services:
    owprov:
      type: ClusterIP
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "none"

haproxy:
  enabled: true
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8080"
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:289708231103:certificate/bfa89c7a-5b64-4a8a-bcfe-ffec655b5285
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "16004,17004,16002,16003,17002,16005,17005,16001,17001,5912,5913"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
